### ISSUE TITLE
Works for "inbound_track" but not for "both_tracks"

### ISSUE THREAD

**Issue by bruno222** [jremi/twilio-media-stream-save-audio-file#1]
Hi @jremi !

This code is awesome, it works great, thank you!

Perhaps you will know this one. 

**What I am doing**

It works when I stream using: `<Stream url='wss://blah.eu.ngrok.io' track='inbound_track' />`

But it does not work when I use: `<Stream url='wss://blah.eu.ngrok.io' track='both_tracks' />`

**The outcome**

It works when I use `inbound_track`, as you can see [in this WAV example](https://drive.google.com/file/d/1dYB-dd-pUW8jKsw4fJOiMdVhdJvPhVC7/view?usp=sharing).

But when I use `both_tracks`, [this is how the WAV file looks like](https://drive.google.com/file/d/12_Y7UrPfpR2t21tF4GWmkJoRiMoMD2H_/view?usp=sharing)

**Docs**

[Twilio docs](https://www.twilio.com/docs/voice/twiml/stream#attributes-track) does not say anything about codec changing when it is `both_tracks`. Do you happen to know why it is failing?

From where did you get [these Hexadecimal headers](https://github.com/jremi/twilio-media-stream-save-audio-file/blob/main/index.js#L29-L87)? I can only think that for both_tracks I need to re-generate those.

Thank you!

**Comment by jremi** [comment]
Hi @bruno222 

Thanks for reaching out.

I am not sure if the wav encoding is the problem or the actual Twilio call is getting down mixed into single channel.

I don't know the exact reason why your running into the issue.

Perhaps this link will help get you further in your troubleshooting:

https://www.twilio.com/changelog/dual-channel-voice-recordings-by-default

**Comment by bruno222** [comment]
Thanks @jremi ! Looks promising! For now, I also found yet another blocker which I need to unblock first. Thank you a lot for your help! Closing this ticket... Cheers!

**Comment by justinlevi** [comment]
Seeing the same issue on my end. 

Here's my JSON media stream output
[MZ9bc263afb37ee6c426613921b47a51df.txt](https://github.com/jremi/twilio-media-stream-save-audio-file/files/12641446/MZ9bc263afb37ee6c426613921b47a51df.txt)

Here are the JSON and WAV files
https://drive.google.com/file/d/1-KOiY-adAZjPuTkOGbOTCYpAxsik9yXz/view?usp=drive_link, https://drive.google.com/file/d/1-J3u6DUQqzJqbW6DVUCSmOrew1oZf_3X/view?usp=drive_link
