### ISSUE TITLE
Cannot set properties of null (setting 'wstream')

### ISSUE THREAD

**Issue by baeckerman83** [jremi/twilio-media-stream-save-audio-file#11]
Hi!
I get an error when using the script. 

I copied all from the readme like:
```
const mediaStreamSaver = new TwilioMediaStreamSaveAudioFile({
  saveLocation: __dirname,
  saveFilename: "my-twilio-media-stream-output",
  onSaved: () => console.log("File was saved!"),
});

wss.on("connection", (ws) => {
  console.log("New connection initiated!");
```

But I get:

```
Starting media stream...
/home/bashur/nodejsweb/node_modules/twilio-media-stream-save-audio-file/index.js:24
    this.websocket.wstream = createWriteStream(this.writeStreamPath, {
                           ^

TypeError: Cannot set properties of null (setting 'wstream')
    at TwilioMediaStreamSaveAudioFile.twilioStreamStart (/home/bashur/nodejsweb/node_modules/twilio-media-stream-save-audio-file/index.js:24:28)
```

**Comment by jremi** [comment]
Hi @baeckerman83,

The error your getting looks like its referencing an older version of the package. `this.websocket.wstream` was updated to `this.wstream` via commit https://github.com/jremi/twilio-media-stream-save-audio-file/commit/75ec54a01f37f9609a173858762929e161578eef

Long story short: Make sure you are running latest version of this package. I think the npm package is not updated with latest version. That might be why you ran into this issue.

For now you can update your **package.json** to pull directly from git repo latest main
```
  // ....
  "dependencies": {
    "twilio-media-stream-save-audio-file": "git+https://github.com/jremi/twilio-media-stream-save-audio-file.git#main"
  },
  // ...
```

Let me know if that fixes for you. I will look to also get the npm package updated.

**Comment by jremi** [comment]
@baeckerman83 

I just updated the npm package to the latest version `0.0.4`. Please update your local project to use the latest `twilio-media-stream-save-audio-file`.

I believe you should be fixed after you do that.

**Comment by baeckerman83** [comment]
Thank you! Now it is working!

**Comment by baeckerman83** [comment]
Thank you! Now it is working!
